FROM maven:3.6.3-jdk-11 AS MAVEN_BUILD
COPY ./ ./
RUN mvn clean package


FROM jdk-11.0.9.1_1-alpine
COPY --from=MAVEN_BUILD /democker/target/democker-0.0.1-SNAPSHOT.jar /demo.jar

CMD ["java", "-jar", "/demo.jar"]